### ISSUE TITLE
Error dragging Jobs

### ISSUE THREAD

**Issue by Updownquark** [Updownquark/Chores#2]
[ERR 24Oct2020  15:41:16.784] java.lang.NullPointerException
	at org.observe.config.ObservableConfigTransform$ObservableConfigBackedCollection.onChange(ObservableConfigTransform.java:411)
	at org.observe.config.ObservableConfigTransform$ObservableConfigValues.onChange(ObservableConfigTransform.java:884)
	at org.observe.config.ObservableConfigFormat$1.parse(ObservableConfigFormat.java:1516)
	at org.observe.config.ObservableConfigFormat$1.parse(ObservableConfigFormat.java:1)
	at org.observe.config.ObservableConfigFormat$AbstractComponentFormat.parseUpdatedField(ObservableConfigFormat.java:1078)
	at org.observe.config.ObservableConfigFormat$EntityConfigFormatImpl.parseUpdatedField(ObservableConfigFormat.java:1467)
	at org.observe.config.ObservableConfigFormat$AbstractComponentFormat.parse(ObservableConfigFormat.java:882)
	at org.observe.config.ObservableConfigTransform$ObservableConfigBackedCollection$ConfigElement.<init>(ObservableConfigTransform.java:576)
	at org.observe.config.ObservableConfigTransform$ObservableConfigEntityValues$ConfigValueElement.<init>(ObservableConfigTransform.java:1036)
	at org.observe.config.ObservableConfigTransform$ObservableConfigEntityValues.createElement(ObservableConfigTransform.java:1018)
[ERR  15:41:16.801] 	at org.observe.config.ObservableConfigTransform$ObservableConfigBackedCollection.onChange(ObservableConfigTransform.java:420)
	at org.observe.config.ObservableConfigTransform$$Lambda$135/1332742800.accept(Unknown Source)
	at org.observe.Observable$2.onNext(Observable.java:58)
	at org.observe.config.ObservableConfig.lambda$9(ObservableConfig.java:1174)
	at org.observe.config.ObservableConfig$$Lambda$699/1276817977.accept(Unknown Source)
	at org.qommons.collect.ListenerList.forEach(ListenerList.java:450)
[ERR  15:41:16.802] 	at org.observe.config.ObservableConfig._fire(ObservableConfig.java:1169)
	at org.observe.config.ObservableConfig.fire(ObservableConfig.java:1160)
	at org.observe.config.ObservableConfig.addChild(ObservableConfig.java:1020)
	at org.observe.config.ObservableConfig.addChild(ObservableConfig.java:1009)
	at org.observe.config.ObservableConfig.moveChild(ObservableConfig.java:1034)
	at org.observe.config.ObservableConfigTransform$ObservableConfigBackedCollection$OCBCCollection.move(ObservableConfigTransform.java:818)
	at org.observe.util.SafeObservableCollection.move(SafeObservableCollection.java:287)
	at org.observe.util.swing.SimpleTableBuilder$TableBuilderTransferHandler.importData(SimpleTableBuilder.java:1015)
	at javax.swing.TransferHandler$DropHandler.drop(Unknown Source)
	at java.awt.dnd.DropTarget.drop(Unknown Source)
	at javax.swing.TransferHandler$SwingDropTarget.drop(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer.processDropMessage(Unknown Source)
[ERR  15:41:16.804] 	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchDropEvent(Unknown Source)
	at sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.dispatchEvent(Unknown Source)
	at sun.awt.dnd.SunDropTargetEvent.dispatch(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processDropTargetEvent(Unknown Source)
[ERR  15:41:16.805] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$400(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
[ERR  15:41:16.806] 	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
[ERR  15:41:16.807] 	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[ERR  15:41:16.808] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Updownquark** [comment]
I believe I've fixed this in the latest release
